imx-boot-signature: Add var-hab-certs:do_deploy dependency
The imx-boot:do_compile task expects files provided by var-hab-certs:do_deploy.
If that task hasn't run beforehand, the required files are missing, leading to
a build failure.

Adds var-habs-certs.do_deploy to imx-boot.do_compile:

$ bitbake -g imx-boot
$ grep "imx-boot.do_compile" task-depends.dot
...
"imx-boot.do_compile" -> "imx-atf.do_deploy"
"imx-boot.do_compile" -> "imx-boot-firmware-files.do_deploy"
"imx-boot.do_compile" -> "imx-boot.do_configure"
"imx-boot.do_compile" -> "u-boot-variscite.do_deploy"
"imx-boot.do_compile" -> "var-hab-certs.do_deploy"
...

Fixes:
ERROR: imx-boot-1.0-r0 do_compile: Could not find '/workdir/build_xwayland/tmp/deploy/images/imx8mq-var-dart/imx-cst/crts/SRK_1_2_3_4_fuse.bin'
ERROR: imx-boot-1.0-r0 do_compile: ExecutionError('/workdir/build_xwayland/tmp/work/imx8mq_var_dart-poky-linux/imx-boot/1.0/temp/run.do_compile.14777', 1, None, None)
ERROR: Logfile of failure stored in: /workdir/build_xwayland/tmp/work/imx8mq_var_dart-poky-linux/imx-boot/1.0/temp/log.do_compile.14777
ERROR: Task (/workdir/sources/meta-imx/meta-imx-bsp/recipes-bsp/imx-mkimage/imx-boot_1.0.bb:do_compile) failed with exit code '1'

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>